/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLService.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API

#import "GTLServiceConstants.h"

#import "GTLServiceJsonMap.h"
#import "GTLServiceKeyWrapper.h"
#import "GTLServiceResponse.h"
#import "GTLServiceUserDetailsWrapper.h"
#import "GTLServiceInfoWrapper.h"

#import "GTLQueryService.h"
#import "GTLServiceService.h"
