/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API

#import "GTLServiceConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeServiceUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
