/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceJsonMap.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceJsonMap (0 custom class methods, 0 custom properties)

#import "GTLServiceJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLServiceJsonMap
//

@implementation GTLServiceJsonMap
@end
