/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceResponse (0 custom class methods, 4 custom properties)

#import "GTLServiceResponse.h"

#import "GTLServiceJsonMap.h"
#import "GTLServiceInfoWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLServiceResponse
//

@implementation GTLServiceResponse
@dynamic data, error, info, responseMessage;
@end
