/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceKeyWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceKeyWrapper (0 custom class methods, 1 custom properties)

#import "GTLServiceKeyWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLServiceKeyWrapper
//

@implementation GTLServiceKeyWrapper
@dynamic key;
@end
