/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceUserDetailsWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   service/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceUserDetailsWrapper (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLServiceUserDetailsWrapper
//

@interface GTLServiceUserDetailsWrapper : GTLObject
@property (nonatomic, retain) NSNumber *age;  // intValue
@property (nonatomic, copy) NSString *city;
@property (nonatomic, copy) NSString *cityId;
@property (nonatomic, copy) NSString *country;
@property (nonatomic, copy) NSString *place;
@property (nonatomic, copy) NSString *gender;
@property (nonatomic, copy) NSString *headline;
@property (nonatomic, retain) NSNumber *liveChatEnabled;  // boolValue

@property (nonatomic, strong, readonly) NSString *location;
@end
